### ISSUE TITLE
No support for multiple channels on Slack

### ISSUE THREAD

**Issue by digitalnomd** [Standup-and-Prosper/standup-and-prosper-sdk-py#1]
Hello! I'm trying to use the Slack integration for my team but some of my teammates have it installed on multiple channels and are unable to select the channel in which to give their standup by using the `/standup start` command. The issue is that when they enter that command they're prompted with a message asking for them to select a channel in which to give their standup. However, clicking the channel name doesn't have any effect.

**Comment by wparad** [comment]
It's possible there is an issue with the configuration, can you send us your team domain name/team id and the channel names to our support DL [standup-support@teaminator.io](mailto:standup-support@teaminator.io).
